### ISSUE TITLE
Attempting to join with !sprint [word_count] when there is no active sprint causes traceback

### ISSUE THREAD

**Issue by ZacharyPuls** [ZacharyPuls/sprintathon#1]
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/discord/ext/commands/bot.py", line 903, in invoke
    await ctx.command.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/discord/ext/commands/core.py", line 855, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/usr/local/lib/python3.7/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: NameError: name 'active_sprint' is not defined

**Comment by ZacharyPuls** [comment]
Fixed by PR #26
