### ISSUE TITLE
Running !leaderboard Command Without Active Spr*ntathon Gives Traceback

### ISSUE THREAD

**Issue by ZacharyPuls** [ZacharyPuls/sprintathon#20]
Ignoring exception in command leaderboard:
Traceback (most recent call last):
  File "C:\Users\zach\PycharmProjects\sprintathon\venv\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:/Users/zach/PycharmProjects/sprintathon/main.py", line 465, in print_leaderboard
    await print_sprintathon_leaderboard(ctx)
  File "C:/Users/zach/PycharmProjects/sprintathon/main.py", line 168, in print_sprintathon_leaderboard
    for sprintathon_member in active_sprintathon.get_members():
NameError: name 'active_sprintathon' is not defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\zach\PycharmProjects\sprintathon\venv\lib\site-packages\discord\ext\commands\bot.py", line 903, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\zach\PycharmProjects\sprintathon\venv\lib\site-packages\discord\ext\commands\core.py", line 855, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\zach\PycharmProjects\sprintathon\venv\lib\site-packages\discord\ext\commands\core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: NameError: name 'active_sprintathon' is not defined

**Comment by ZacharyPuls** [comment]
Fixed by PR #26.
